name: shader_buffers_example
description: Shader buffers example
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  
  flutter:
    sdk: flutter

  shader_buffers:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
  
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  shaders:
    - assets/shaders/arrows.frag
    - assets/shaders/mouse1.frag
    - assets/shaders/mouse2.frag
    - assets/shaders/shader1_main.frag
    - assets/shaders/shader1_bufferA.frag
    - assets/shaders/shader2_main.frag
    - assets/shaders/shader2_bufferA.frag
    - assets/shaders/test.frag
    - assets/shaders/water.frag
    - assets/shaders/page_curl.frag
    - assets/shaders/noise_fade.frag
    - assets/shaders/ripple.frag
    - assets/shaders/test_isself_buffer_a.frag
    - assets/shaders/test_isself_main.frag
    - assets/shaders/filters/black.frag
    - assets/shaders/filters/white.frag

