name: shader_buffers
description: >-
  Using shaders to feed a shader. Make shaders simplier
  to use with a focus on the ShaderToy.com website.
version: 1.1.1
homepage: https://github.com/alnitak/shader_buffers
issue_tracker: https://github.com/alnitak/shader_buffers/issues
repository: https://github.com/alnitak/shader_buffers
topics:
  - shader
  - shadertoy

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0

flutter:

  assets:
    - assets/

